// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();
const path = require("path"); 
const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });


  const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, "uploads/"),
  filename: (req, file, cb) => {
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const upload2 = multer({ storage });


router.post("/login", dataController.login);
router.post("/VerifyCustomer", dataController.VerifyCustomer);
router.post('/verifyOtp', dataController.verifyOtp);
router.post("/signup", dataController.signUp);
router.post("/city", dataController.getCity)
router.post("/variant", dataController.getvariant)
router.post("/uom", dataController.getuom)
router.post("/country", dataController.getCountry)
router.post("/state", dataController.getState)
router.post("/status", dataController.getStatus)
router.post("/Shift", dataController.getShift)
router.post("/Transaction", dataController.getTransaction)
router.post("/gender", dataController.getGender)
router.post("/Loginorout", dataController.getLoginorout)
router.get("/", dataController.getAllData)
router.post("/add", upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.addData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.get ("/userData", dataController.getAlluserData)
router.get("/WareHouseData",dataController.getAllWareHouseData)
router.post("/AddWareHousedata",dataController.AddWareHouseData)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/userdelete", dataController.UserdeleteData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.post("/warehouseupdate", dataController.WareHousesaveEditedData)
router.get("/attrihdrdata",dataController.getAllattributehdrData)
router.post("/addattriData",dataController.addattrihdrData)
//router.post("/updattriData",dataController.updattrihdrData)
router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.get("/hdrcode", dataController.gethdrcode)
router.post("/taxtype", dataController.gettaxtype)
router.get("/IntermediaryheaderData", dataController.getAllIntermediaryheaderData)
router.post("/AddIntermediaryheaderData", dataController.addIntermediaryHdrData)
router.get("/IntermediarydetailData", dataController.getAllIntermediaryDetailData)
router.post("/addIntermediaryDetailData", dataController.addIntermediaryDetailData)
router.post("/updateIntermediaryDetailData", dataController.updintermediarydetData)
router.get("/UomData", dataController.getAllUOMData)
router.post("/addUomData", dataController.addUOMData)
router.post("/deleteIntermediaryHeaderData", dataController.deleteIntermediaryHeaderData)
router.post("/deleteIntermediaryDetailData", dataController.deleteIntermediaryDetailData)
router.post("/delPer", dataController.getDeletepermission)
router.post("/regbrand", dataController.getregisterbrand)
router.post("/ourbrand", dataController.getourbrand)
router.get("/inthdrcode", dataController.getInthdrcode)
router.post("/TaxHdrData", dataController.getAllTaxHdrData)
router.post("/addTaxHdrData", dataController.addTaxHdrData)
router.get("/TaxDetailsData", dataController.getAllTaxDetailsData)
router.post("/addTaxDetailsData",dataController.addTaxDetailsData)
router.post("/updTaxDetailsData",dataController.updtaxdetaildata)
router.post("/ItemBrandData",dataController.getAllItemBrandData)
router.post("/delItemBrandData",dataController.deleteItemData)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.post("/warehousedelete",dataController.WareHousedeleteData)
router.get("/VendorHdrData",dataController.getAllVendorHdrData)
router.post("/addVendorHdrData",dataController.addVendorHdrData)
router.get("/VendorDetData", dataController.getAllVendorDetData)
router.post("/addVendorDetData",dataController.addVendorDetData)
router.post("/updvendordetData",dataController.updvendordetData)
router.post("/deleteVendorData",dataController.VendordeleteData)
router.post("/vendorcode",dataController.getvendorcode)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.get("/usercode",dataController.getUsercode)
router.post("/Usertype", dataController.getUsertype)
router.get("/Companyno",dataController.getCompanyno)
router.get("/locationno",dataController.getLocationno)
router.post("/paytype", dataController.getPaytype)
router.post("/purchasetype", dataController.getPurchasetype)
router.post("/salestype", dataController.getSalestype)
router.post("/ordertype", dataController.getordertype)
router.post("/vendorcodename", dataController.getVendorcodename)
router.post("/roleid", dataController.getroleid)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/itemsearchdata",dataController.getitemsearchdata)
router.post("/warehouseSearchdata",dataController.getwarehouseSearchdata)
router.post("/taxpercenttype",dataController.gettypeperdata)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/location_no",dataController.locationsaveEditedData)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/itempursearchdata",dataController.getitempursearchdata)
router.post("/getpursearchdata",dataController.getpursearchdata)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/vendorsearchdata",dataController.getvendorSearchdata)
router.post("/purchasehdrdata",dataController.getAllpurhdrData)
router.post("/addpurchasehdrdata",dataController.addpurchaseheader)
router.post("/purhdetData",dataController.getAllpurhdetData)
router.post("/addpurhdetData",dataController.addpurchasedetail)
router.post("/purtaxdata",dataController.getAllpurtaxData)
router.post("/purtaxdetail",dataController.addpurtaxdetail)
router.post("/TotalAmountCalculation",dataController.getTotalAmountCalculation)
router.post("/PartyCode",dataController.getPartyCode)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/intermediarySearchdata",dataController.getintermediarySearchdata)
router.post("/addpurchasereturnheader",dataController.addpurchasereturnheader)
router.post("/getpurchrethdrdata",dataController.getAllpurchaseheaderreturnData)
router.post("/getpurchasereport",dataController.getpurchasereport)
router.post("/taxSearchdata",dataController.gettaxSearchdata)
router.post("/getitemcodepurdata",dataController.getitemcodepurdata)
router.get("/smcode",dataController.getsalesmancode)
router.get("/trcode",dataController.gettransportcode)
router.get("/brcode",dataController.getbrokercode)
router.post("/saleshdrdata",dataController.getAllsaleshdrData)
router.post("/addsaleshdrdata",dataController.addsaleshdr)
router.post("/addpurchasehdrdata",dataController.addpurchaseheader)
router.post("/addsalesdetData",dataController.addsalesdetdetail)
router.post("/addpurhdetData",dataController.addpurchasedetail)
router.post("/transactiontype",dataController.gettranstype)
router.post("/salestaxData",dataController.getAllsalestaxdetData)
router.post("/addinventorytaxdetail",dataController.addinventorytaxdetail)
router.post("/getPurchaseData",dataController.getPurchaseData)
router.post("/salessearchdata",dataController.getsalessearchdata)
router.post("/SalesRetHdrData",dataController.getAllSalesRetHdrData)
router.post("/addSalesRetHdr",dataController.addSalesRetHdr)
router.post("/getpurchasereturnit",dataController.getpurchasereturnit)
router.post("/getpurchasereturntax",dataController.getpurchasereturntax)
router.get("/Numberseries",dataController.getAllNumberseries)
router.post("/addNumberseries",dataController.addNumberseries)
router.post("/numberseriessearchdata",dataController.getnumberseriessearchdata)
router.post("/saveEditedNumberseriesData",dataController.saveEditedNumberseriesData)
router.post("/refNumberToHeaderPrintData",dataController.refNumberToHeaderPrintData)
router.post("/refNumberToDetailPrintData",dataController.refNumberToDetailPrintData)
router.post("/refNumberToSumTax",dataController.refNumberToSumTax)
router.post("/addpurchasereturntaxdetails",dataController.addpurchasereturntaxdetails)
router.post("/addpurchasereturndetails",dataController.addpurchasereturndetails)
router.post("/getpurchasereturndetails",dataController.getpurchasereturndetails)
router.post("/getpurchasereturntaxdetails",dataController.getpurchasereturntaxdetails)
router.post("/getAllDashboardData",dataController.getAllDashboardData)
router.post("/getSalesItemAmountCalculation",dataController.getSalesItemAmountCalculation)
router.post("/ItemPrice",dataController.getItemPrice)
router.post("/SalesTotalAmountCalculation",dataController.SalesTotalAmountCalculation)
router.post("/Product",dataController.getProduct)
router.post("/getPurchaseReturnItemAmountCalculation",dataController.getPurchaseReturnItemAmountCalculation)
router.post("/screentype",dataController.getscreentype)
router.post("/DashboardItemData",dataController.getDashboardItemData)
router.post("/DashboardStockData",dataController.getDashboardStockData)
router.get("/getDashboardSaleYear",dataController.getDashboardSaleYear)
router.get("/getDashboardSaleMonth",dataController.getDashboardSaleMonth)
router.post("/getsalesreport",dataController.getsalesreport)
router.post("/salemonthreport",dataController.getsalemonthreport,)
router.get("/getallsalesreport",dataController.getallsalesreport)
router.get("/salereportdailywise",dataController.getallsalereportdailywise)
router.get("/salereportmonthlywise",dataController.getallsalereportmonthlywise)
router.get("/salereportyearlywise",dataController.getallsalereportyearlywise)
router.post("/Passwords",dataController.Passwords)
router.post("/refNumberTosalesHeaderPrintData",dataController.refNumberTosalesHeaderPrintData)
router.post("/refNumberTosalesDetailPrintData",dataController.refNumberTosalesDetailPrintData)
router.post("/refNumberTosalesSumTax",dataController.refNumberTosalesSumTax)
// router.get("/getpurreturnkey ",dataController.getpurreturnkey )
router.post("/getitemstockvalue",dataController.getitemstockvalue )
router.post("/getAllItemVarient",dataController.getAllItemVarient )
router.post("/itemvairentname",dataController.getitemvairentname )
router.post("/DashboardUnit",dataController.getAllUOM )
router.post("/uomdetail",dataController.getAlluomdetail)
router.post("/numberseriesdeleteData",dataController.numberseriesdeleteData)
router.post("/onlywarehsearchdata",dataController.getonlywarehsearchdata)
router.post("/getusercompany",dataController.getusercompany)
router.post('/updateitemdata',dataController. updateitemData);
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.post("/getSalesReturnItemAmountCalculation",dataController.getSalesReturnItemAmountCalculation)
router.post("/getSalesData",dataController.getSalesData)
router.post("/getSalesDetail",dataController.getSalesDetail)
router.post("/getSalesTaxDetail",dataController.getSalesTaxDetail)
router.post("/getWarehouseCodeData",dataController.getWarehouseCodeData)
router.post("/SalesreturnTotalAmountCalculation",dataController.SalesreturnTotalAmountCalculation)
router.get("/userscreenmap", dataController.getAlluserscreenmap)
router.post("/adduserscreenmap",dataController.adduserscreenmap)
router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/getAllSalesRetDetailData",dataController.getAllSalesRetDetailData)
router.post("/addSalesRetDetail",dataController.addSalesRetDetail)
router.post("/addSalesRetTaxDetail",dataController.addSalesRetTaxDetail)
router.post("/getAllSalesRetTaxDetailData",dataController.getAllSalesRetTaxDetailData)
router.post("/customerhdr", dataController.getAllcustomerhdr)
router.post("/addcustomerhdr",dataController.addcustomerhdr)
router.get("/CustomerDetData", dataController.getAllCustomerDetData)
router.post("/addCustomerDetData",dataController.addCustomerDetData)
router.post("/updcustomerdetData",dataController.updcustomerdetData)
router.post("/customercode",dataController.getcustomercode)
router.post("/customerSearchdata",dataController.customerSearchdata)
router.post("/customerdeleteData",dataController.customerdeleteData)
router.get("/openbalance", dataController.getAllopenbalance)
router.post("/addopenbalance",dataController.addopenbalance)
router.post("/openbalsaveEditedData",dataController.openbalsaveEditedData)
router.post("/openingbalancedeleteData",dataController.openingbalancedeleteData)
router.post("/getopeningbalancedata",dataController.getopeningbalanceSearchdata)
router.post("/addadjustment",dataController.addadjustment)
router.post("/adjustmentSearchdata",dataController.getadjustmentSearchdata)
router.post("/updadjustmentData",dataController.updadjustmentData)
router.post("/deleteadjustmentData",dataController.deleteadjustmentData)
router.post("/itemcode", dataController.getitemcode)
router.post("/refNumberToPurchaseReturnHeaderPrintData",dataController.refNumberToPurchaseReturnHeaderPrintData)
router.post("/refNumberToPurchaseReturnDetailPrintData",dataController.refNumberToPurchaseReturnDetailPrintData)
router.post("/refNumberToPurachseReturnSumTax",dataController.refNumberToPurachseReturnSumTax)
router.post("/refNumberToSalesReturnHeaderPrintData",dataController.refNumberToSalesReturnHeaderPrintData)
router.post("/refNumberToSalesReturnDetailPrintData",dataController.refNumberToSalesReturnDetailPrintData)
router.post("/refNumberToSalesReturnSumTax",dataController.refNumberToSalesReturnSumTax)
router.post("/getItemCodeSalesData",dataController.getItemCodeSalesData)
router.post("/getCustomerCode",dataController.getCustomerCode)
router.post("/getCustomerSearchdata",dataController.getCustomerSearchdata)
router.post("/addstocktransferdetail",dataController.addstocktransferdetail)
router.post("/stocktransferSearch",dataController.getstocktransferSearch)
router.post("/updstocktransfer",dataController.updstocktransfer)
router.post("/deletestocktransfer",dataController.deletestocktransfer)
router.post("/purdeletehdrData",dataController.purdeletehdrData)
router.post("/purDeleteDetailData",dataController.purDeleteDetailData)
router.post("/purDeleteTaxData",dataController.purDeleteTaxData)
router.post("/getUserPermission",dataController.getUserPermission)
router.post("/addjournal",dataController.addjournal)
router.post("/getjournalSearch",dataController.getjournalSearch)
router.post("/saveEditjournal",dataController.saveEditjournal)
router.post("/deletejournal",dataController.deletejournal)
router.get("/getwarehousecode", dataController.getwarehousecode)
router.post("/getPurchaseAnalysisChart", dataController.getPurchaseAnalysisChart)
router.post("/getPurchaseDeleteDetails", dataController.getPurchaseDeleteDetails)
router.post("/getpurDeleteDetails", dataController.getpurDeleteDetails)
router.post("/purdeletedunit", dataController.purdeletedunit)
router.post("/purdeletedtax", dataController.purdeletedtax)
router.post("/facereg", dataController.facereg);
router.post("/getSalesAnalysisChart", dataController.getSalesAnalysisChart);
router.post("/getRefSalesDelete", dataController.getRefSalesDelete);
router.post("/getsalesdelsearchdata", dataController.getsalesdelsearchdata);
router.post("/saledelsearchitem", dataController.saledelsearchitem);
router.post("/salesdelsearchtax", dataController.salesdelsearchtax);
router.post("/saledeletehdrData", dataController.saledeletehdrData);
router.post("/saleDeleteDetailData", dataController.saleDeleteDetailData);
// router.post("/saleDeleteTaxData", dataController.salesdelsearchtax);
router.post("/addstocktransferhdr",dataController.addstocktransferhdr)
router.post("/gettaxitemsales",dataController.gettaxitemsales)
router.post("/getDashboardPurchase",dataController.  getDashboardPurchase)
router.post("/getDashboardSales",dataController.getDashboardSales)
router.post("/getStockKey",dataController.getStockKey)
router.post("/StockTransferDetail",dataController.StockTransferDetail)
router.post("/getDashboardItemSales",dataController.  getDashboardItemSales)
router.post("/StockTransferItemAmountCalculation",dataController.StockTransferItemAmountCalculation)
router.post("/deletestocktransferhdr",dataController.deletestocktransferhdr)
router.post("/deletestocktransfer",dataController.deletestocktransfer)
router.post("/refNumberToStockDetailPrintData",dataController.refNumberToStockDetailPrintData)
router.post("/addBaseaccountData",dataController.addBaseaccountData)
router.get("/getAllBaseAccountData",dataController.getAllBaseAccountData)
router.post("/getsearchdataBase",dataController.getsearchdataBase)
router.post("/updateBase",dataController.updateBase)
router.post("/deleteBaseData",dataController.deleteBaseData)
router.post("/addUserAccGrp",dataController.addUserAccGrp)
router.post("/getsearchUserAccGrp", dataController.getsearchUserAccGrp);
router.post("/updUserAccGrp", dataController.updUserAccGrp);
router.post("/deleteUserAccGrp",dataController.deleteUserAccGrp)
router.get("/getStdAccGrp",dataController.  getStdAccGrp)
router.get("/getBaseAccGrp",dataController.  getBaseAccGrp)
// router.post("/deleteBaseData",dataController.deleteBaseData)
router.post("/AddStandardAccountData",dataController.addstandardaccountData)
router.get("/getAllStandardAccountData",dataController.getAllStandardAccountData)
router.get("/getbasaccode",dataController.getbasaccode)
router.post("/gettaxitempur",dataController.gettaxitempur)
router.post("/getCurrentStock",dataController.getCurrentStock)
router.post("/getNegativeStock",dataController.getNegativeStock)  
router.post("/getstandardsearchdata",dataController.getstandardsearchdata)
router.post("/deleteStdAccGrp",dataController.deleteStdAccGrp)
router.post("/updStdAccGrp",dataController.updStdAccGrp)
router.post("/salesDeleteTaxData",dataController.saleDeleteTaxData)
router.post("/warehouseDashboard",dataController.warehouseDashboard)
router.post("/deleteTaxData",dataController.deleteTaxData)
router.post("/updTaxdetData",dataController.updTaxdetData)
router.post("/getpurchasereturnView",dataController.getpurchasereturnView)
router.post("/UomChart",dataController.UomChart)
router.post("/TransDetail",dataController.Transdetail)
router.post("/partytransdetail",dataController.partytransdetail)
router.post("/alltransdetail",dataController.alltransdetail)
router.post("/datetransdetail",dataController.datetransdetail)
router.post("/getSalesreturnView",dataController.getSalesreturnView)
router.post("/getpurreturnsearchViewdata",dataController.getpurreturnsearchViewdata)
router.post("/getwarehousedrop",dataController.getwarehousedrop)
router.post("/varientChart",dataController.varientChart)
router.post("/addAccountName",dataController.addAccountName)
router.post("/getAccNameSearch",dataController.getAccNameSearch)
router.post("/updateAccName",dataController.updateAccName)
router.post("/AccNameDelete",dataController.AccNameDelete)
router.get("/AllAccNameData",dataController.getAllAccNameData)
router.post("/getsalesreturnsearchViewdata",dataController.getsalesreturnsearchViewdata)
router.post("/SalesReturnTaxView",dataController.SalesReturnTaxView)
router.post("/SalesReturnDetailView",dataController.SalesReturnDetailView)
router.post("/getitemsalsearchdata",dataController.getitemsalsearchdata)
router.post("/gettransdetailchart",dataController.gettransdetailchart)
router.post("/getpurchasereturntaxView",dataController.getpurchasereturntaxView)
router.post("/getpurchasereturnitView",dataController.getpurchasereturnitView)
router.get("/getDateRange",dataController.getDateRange)
router.post("/getUsercodename",dataController.getUsercodename)
router.post("/getAccountCode",dataController.getAccountCode)
router.post("/addbankAccount",upload.single('bank_paymentQRCode'),dataController.addbankAccount)
router.post("/getacctype",dataController.getacctype)
router.post("/updatebankAcc",dataController.updatebankAcc)
router.post("/getbankaccSearch",dataController.getbankaccSearch)
router.post("/addDeliveryChallanheader",dataController.addDeliveryChallanheader)
router.post("/getAllDChdrData",dataController.getAllDChdrData)
router.post("/DCdeletehdrData",dataController.DCdeletehdrData)
router.post("/getAllDCdetData",dataController.getAllDCdetData)
router.post("/addDeliveryChallandetail",dataController.addDeliveryChallandetail)
router.post("/DCdeletedetData",dataController.DCdeletedetData)
router.post("/getofftype",dataController.getofftype)
router.post("/addItemBrandData",upload.single('item_images'),dataController.addItemBrandData)
router.post("/addQuotationheader",dataController.addQuotationheader)
router.post("/getAllquotehdrData",dataController.getAllquotehdrData)
router.post("/quotedeletehdrData",dataController.quotedeletehdrData)
router.post("/getAllquotedetData",dataController.getAllquotedetData)
router.post("/addquotationdetail",upload.single('item_images'),dataController.addquotationdetail)
router.post("/quotedeletedetData",dataController.quotedeletedetData) 
router.post("/refNumberToQuotationHeaderPrintData",dataController.refNumberToQuotationHeaderPrintData) 
router.post("/refNumberToQuotationDetailPrintData",dataController.refNumberToQuotationDetailPrintData) 
router.post("/getAllquotetaxData",dataController.getAllquotetaxData)
router.post("/addquotetaxdetail",dataController.addquotetaxdetail)
router.post("/quoteDeleteTaxData",dataController.quoteDeleteTaxData)
router.post("/refNumberToQuoteSumTax",dataController.refNumberToQuoteSumTax)
router.post("/deliverychallanhdrprint",dataController.deliverychallanhdrprint) 
router.post("/deliverychallandetprint",dataController.deliverychallandetprint) 
router.post("/addPurchaseOrderheader",dataController.addPurchaseOrderheader)
router.post("/getAllPOhdrData",dataController.getAllPOhdrData)
router.post("/POdeletehdrData",dataController.POdeletehdrData)
router.post("/getItemCodeQuotation",dataController.getItemCodeQuotation)
router.post("/addPurchaseOrderdetail",dataController.addPurchaseOrderdetail)
router.post("/getAllPOdetData",dataController.getAllPOdetData)
router.post("/POdeletedetData",dataController.POdeletedetData)
router.post("/addPOtaxdetail",dataController.addPOtaxdetail)
router.post("/getAllPOtaxData",dataController.getAllPOtaxData)
router.post("/PODeleteTaxData",dataController.PODeleteTaxData)
router.post("/purchaseOrderdetprint",dataController.purchaseOrderdetprint) 
router.post("/purchaseOrderhdrprint",dataController.purchaseOrderhdrprint) 
router.post("/refNumberToPOSumTax",dataController.refNumberToPOSumTax) 
router.post("/getItem",dataController.getItem) 
router.post("/addProductHeader",upload.single('Product_img'),dataController.addProductHeader)
router.get("/getAllproducthdrData",dataController.getAllproducthdrData)
router.post("/productdeletehdrData",dataController.productdeletehdrData)
router.post("/getProductcode",dataController.getProducthdrcode)
router.post("/addProductDetail",dataController.addProductdet)
// router.post("/ProductDelete",dataController.ProductDelete)
router.post("/ProudctUpdate",dataController.ProudctUpdate)
router.post("/getItemCodeDcData",dataController.getItemCodeDcData) 
router.post("/getDcSearchData",dataController.getDcSearchData) 
router.post("/getDcDetailView",dataController.getDcDetailView) 
router.post("/getQuotationSearchData",dataController.getQuotationSearchData) 
router.post("/getQuotationDetailView",dataController.getQuotationDetailView) 
router.post("/getQuotationTaxDetailView",dataController.getQuotationTaxDetailView) 
router.post("/getPOSearchData",dataController.getPOSearchData) 
router.post("/getPODetailView",dataController.getPODetailView) 
router.post("/getPOTaxDetailView",dataController.getPOTaxDetailView) 
router.post("/getproductsearch",dataController.getproductsearch) 
router.post("/getQuotation",dataController.getQuotation) 
router.post("/getDeliveryChallan",dataController.getDeliveryChallan) 
router.post("/getPurchaseOrder",dataController.getPurchaseOrder) 
router.post("/getQuotationPeriod",dataController.getQuotationPeriod) 
router.post("/getPOperiod",dataController.getPOperiod) 
// router.post("/delproductdetdata",dataController.ProductDetailDelete) 
router.post("/purreturndeletehdrData",dataController.purreturndeletehdrData) 
router.post("/purreturndeletedetData",dataController.purreturndeletedetData) 
router.post("/purreturndeletetaxdetData",dataController.purreturndeletetaxdetData) 
router.post("/salereturndeletehdrData",dataController.salereturndeletehdrData) 
router.post("/salereturndeletedetData",dataController.salereturndeletedetData) 
router.post("/salereturndeletetaxdetData",dataController.salereturndeletetaxdetData)
router.post("/ProductCodeDetail",dataController.ProductCodeDetail) 
router.get("/getAllsalesdetData",dataController.getAllsalesdetData) 
router.get("/getAllsalesdetData",dataController.getAllsalesdetData) 
router.post("/addtestreport",upload.single('file'),dataController.addtestreport)
router.post("/gettestreports",dataController.gettestreports) 
router.get("/getAlltestreports",dataController.getAlltestreports) 
router.post("/Updtestreport",dataController. Updtestreport) 
router.post("/getDCperiod",dataController.getDCperiod)
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/purchaseEditHeader",dataController.purchaseEditHeader)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/UserRole",dataController.getUserRole)
router.get("/getAllInventoryReceiptsDetails",dataController.getAllInventoryReceiptsDetails) 
router.post("/addInventoryReceiptsDetails",dataController.addInventoryReceiptsDetails) 
router.post("/deleteInventoryReceiptsDetails",dataController.deleteInventoryReceiptsDetails) 
router.post("/addInventoryReceiptsheader",dataController.addInventoryReceiptsheader)
router.post("/inventoryReceiptsDelete",dataController.inventoryReceiptsDelete)
router.get("/inventoryReceiptsAll",dataController.inventoryReceiptsAll)
router.post("/addInventoryReturnheader",dataController.addInventoryReturnheader)
router.post("/inventoryReturnHeaderDelete",dataController.inventoryReturnHeaderDelete)
router.post("/inventoryReturnHeaderAll",dataController.inventoryReturnHeaderAll)
router.post("/addInventoryReturndetails",dataController.addInventoryReturndetails)
router.post("/InventoryReturnDeleteDetailData",dataController.InventoryReturnDeleteDetailData)
router.post("/getAllInventoryReturndetailData",dataController.getAllInventoryReturndetailData)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/AddEmployeeInfo",dataController.AddEmployeeInfo)
router.post("/EmployeeInfodelete",dataController.EmployeeInfodelete)
router.get("/EmployeinfoAll",dataController.EmployeinfoAll)
router.post("/AddDepartment",dataController.AddDepartment)
router.get("/ViewEmployee",dataController.ViewEmployee)
router.post("/EmployeeUpdate",dataController.EmployeeUpdate)
router.post("/getInventoryTransaction",dataController.getInventoryTransaction)
router.post("/inventoryIssuanceAll",dataController.inventoryIssuanceAll)
router.post("/inventoryIssuanceDelete",dataController.inventoryIssuanceDelete)
router.post("/addInventoryIssuancehdr",dataController.addInventoryIssuancehdr)
router.post("/getAllInventoryIssuancedetailData",dataController.getAllInventoryIssuancedetailData)
router.post("/InventoryIssuanceDeleteDetailData",dataController.InventoryIssuanceDeleteDetailData)
router.post("/addInventoryIssuancedetails",dataController.addInventoryIssuancedetails)
router.post("/getInventoryReturn",dataController.getInventoryReturn)
router.post("/getInventoryReturnDetails",dataController.getInventoryReturnDetails)
router.post("/getInventoryReceipt",dataController.getInventoryReceipt)
router.post("/getInventoryReceiptDetail",dataController.getInventoryReceiptDetail)
router.post("/getInventoryIssued",dataController.getInventoryIssued)
router.post("/getInventoryIssuedDetail",dataController.getInventoryIssuedDetail)
router.post("/InventoryReturnHeaderPrint",dataController.InventoryReturnHeaderPrint)
router.post("/InventoryReturnDetailPrint",dataController.InventoryReturnDetailPrint)
router.post("/InventoryReceiptHeaderPrint",dataController.InventoryReceiptHeaderPrint)
router.post("/InventoryReceiptDetailPrint",dataController.InventoryReceiptDetailPrint)
router.post("/InventoryIssuedHeaderPrint",dataController.InventoryIssuedHeaderPrint)
router.post("/InventoryIssuedDetailPrint",dataController.InventoryIssuedDetailPrint)
router.post("/addAssetsAllocationheader",dataController.addAssetsAllocationheader)
router.post("/AssetsAllocationdelete",dataController.AssetsAllocationdelete)
router.post("/GetAllAssetsAllocationHdr",dataController.GetAllAssetsAllocationHdr)
router.post("/addAssetsAllocationDeatils",dataController.addAssetsAllocationDeatils)
router.post("/deleteAssetsAllocationDetails",dataController.deleteAssetsAllocationDetails)
router.post("/GetAllAssetsAllocationDetails",dataController.GetAllAssetsAllocationDetails)
router.post("/InventoryReturnSearchData",dataController.InventoryReturnSearchData)
router.post("/InventoryReceiptSearchData",dataController.InventoryReceiptSearchData)
router.post("/InventoryIssuedSearchData",dataController.InventoryIssuedSearchData)
router.post("/AssetsAllocationdeletehdr",dataController.AssetsAllocationdeletehdr)
router.post("/AssetsAllocationdeleteDetails",dataController.AssetsAllocationdeleteDetails)
router.post("/getallAssetsAllocation",dataController.getallAssetsAllocation)
router.post("/getEmptype", dataController.getEmptype)
router.post("/getDept", dataController.getDept)
router.post("/getDesgination", dataController.getDesgination)
router.post("/getallEmployee", dataController.getallEmployee)
router.post("/EmployeeDelete", dataController.EmployeeDelete)
router.post("/EmployeeEditData", dataController.EmployeeEditData)
router.post("/getallEmployeePopUp", dataController.getallEmployeePopUp)
router.post("/getallAssetsAllocationsaved", dataController.getallAssetsAllocationsaved)
router.post("/productDeleteDetails", dataController.productDeleteDetails)
router.post("/ProductData", dataController.getProductData)
router.post("/ProductDetail", dataController.getProductDetail)
router.post("/ProductSearchData", dataController.ProductSearchData)
router.post("/getallassetsdetails", dataController.getallassetsdetails)
router.post("/Condition", dataController.getCondition)
router.post("/PurchaseAuthHdr", dataController.PurchaseAuthHdr)
router.post("/PurchaseAuthDetail", dataController.PurchaseAuthDetail)
router.post("/PurchaseAuthTaxDetail", dataController.PurchaseAuthTaxDetail)
router.post("/SalesAuthHdr", dataController.SalesAuthHdr)
router.post("/SalesAuthDetail", dataController.SalesAuthDetail)
router.post("/SalesAuthTaxDetail", dataController.SalesAuthTaxDetail)
router.post("/AddDesgination", dataController.AddDesgination)
router.get("/GetAllDesgination", dataController.GetAllDesgination)
router.post("/desginationDelete", dataController.desginationDelete)
router.post("/UpdateDesgintion", dataController.DesgintionEditData)
router.post("/DesginationSerachData", dataController.desgsearch)
router.post("/DepartmentSerachData", dataController.DeptSearch)
router.post("/UpdateDepartment", dataController.DepartmetEditData)
router.post("/DeleteDepartment", dataController.departmentDelete)
router.post("/PurchReturnAuthHdr", dataController.PurchReturnAuthHdr)
router.post("/PurchReturnAuthDetail", dataController.PurchReturnAuthDetail)
router.post("/PurchReturnAuthTaxDetail", dataController.PurchReturnAuthTaxDetail)
router.post("/SalesReturnAuthHdr", dataController.SalesReturnAuthHdr)
router.post("/SalesReturnAuthDetail", dataController.SalesReturnAuthDetail)
router.post("/SalesReturnAuthTaxDetail", dataController.SalesReturnAuthTaxDetail)
// router.post("/updateitemDataTest",upload.single('item_images'),dataController.updateitemDataTest)
router.post("/UpdateItemImage",upload.single('item_images'),dataController.UpdateItemImage)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/CompanyUpdate",upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/NumberSeriesUpdate", dataController.NumberSeriesUpdate)
router.post("/ItemUpdate",upload.single('item_images'),dataController.ItemUpdate)
router.post("/TaxUpdate", dataController.TaxUpdate)
router.post("/WarehouseUpdates", dataController.WarehouseUpdate)
router.post("/VendorUpdate", dataController.VendorUpdate)
router.post("/addadjustmenthdr",dataController.addadjustmenthdr)
router.post("/Adjustmnetdelhdr",dataController.Adjustmnetdelhdr)
router.post("/adjustmentupdatehdr",dataController.adjustmentupdatehdr)
router.get("/getalladjustmnethdr",dataController.getalladjustmnethdr)
router.post("/addadjustmnetdetails",dataController.addadjustmnetdetails)
router.post("/adjustmnetdeletedetails",dataController.adjustmnetdeletedetails)
router.get("/getalladjustmnetdetails",dataController.getalladjustmnetdetails)
router.post("/addOpeningbalHdr",dataController.addOpeningbalHdr)
router.post("/OpeningBalDelhdr",dataController.OpeningBalDelhdr)
router.post("/OpeningBalanceupHdr",dataController.OpeningBalanceupHdr)
router.get("/GetallopeningBalHdr",dataController.GetallopeningBalHdr)
router.post("/AddOpeningBalanceDetails",dataController.AddOpeningBalanceDetails)
router.post("/OpeningBaldeletedet",dataController.OpeningBaldeletedet)
router.get("/getallopeningBalDet",dataController.getallopeningBalDet)
router.post("/AddJournalHdr",dataController.AddJournalHdr)
router.post("/JournaDeleteHdr",dataController.JournaDeleteHdr)
router.post("/JournalUpdateHdr",dataController.JournalUpdateHdr)
router.get("/GetAllJournalHdr",dataController.GetAllJournalHdr)
router.post("/AddJournalDetails",dataController.AddJournalDetails)
router.post("/JournalDeletedet",dataController.JournalDeletedet)
router.get("/GetAllJournalDet",dataController.GetAllJournalDet)
router.post("/CustomerUpdate", dataController.CustomerUpdate)
router.post("/IntermediaryUpdate", dataController.IntermediaryUpdate)
router.post("/BankAccountUpdate",upload.single('bank_paymentQRCode'), dataController.BankAccountUpdate)
router.post("/DepartmentUpdate",dataController.DepartmentUpdate)
router.post("/DesgintionUpdate",dataController.DesgintionUpdate)
router.post("/EmployeeUpdate",dataController.EmployeeUpdate)
router.post("/BaseAccountUpdate",dataController.BaseAccountUpdate)
router.post("/COAUpdate",dataController.COAUpdate) // charts of Accounts
router.post("/StandardAccUpdate",dataController.StandardAccUpdate) 
router.post("/UserAccGrpUpdate",dataController.UserAccGrpUpdate) 
router.post("/AdjustmnethdrPrint",dataController.AdjustmnethdrPrint)
router.post("/AdjustmnetdetPrint",dataController.AdjustmnetdetPrint)
router.post("/getadjustmentdata",dataController.getadjustmentdata)
router.post("/OpeningBalance",dataController.getOpeningBalance)
router.post("/OpeningBalanceDetails",dataController.getOpeningBalanceDetails)
router.post("/OpeningBalanceSearchData",dataController.OpeningBalanceSearchData)
router.post("/ObHeaderPrint",dataController.ObHeaderPrint)
router.post("/ObDetailPrint",dataController.ObDetailPrint)
router.post("/AdjustmentSearch",dataController.AdjustmentSearch)
router.post("/JournalHdrPrint",dataController.JournalHdrPrint)
router.post("/JournalDetPrint",dataController.JournalDetPrint)
router.post("/Journalsearch",dataController.Journalsearch)
router.post("/AdjustmentDetails",dataController.getAdjustmentDetails)
router.post("/getJournaldata",dataController.getJournaldata)
router.post("/getJournalDetails",dataController.getJournalDetails)
router.post("/getEvent", dataController.getEvent)
router.post("/purauthstatus", dataController.purauthstatus)
router.post("/salauthstatus", dataController.salauthstatus)
router.post("/salretauthstatus", dataController.salretauthstatus)
router.post("/purretauthstatus", dataController.purretauthstatus)
//router.post("/updpurchasedetail",dataController.updpurchasedetail)
router.post("/ItemAmountCalculation",dataController.getPurItemAmountCalculation)
router.post("/taxinvoiceitemamt", dataController.gettaxinvoiceitemamt)
router.post("/taxinvoicetotamt", dataController.gettaxinvoicetotamt)
router.post("/addtaxInvoicehdr",dataController.addtaxInvoicehdr) 
router.post("/TaxInvoicehdrDelteData",dataController.TaxInvoicehdrDelteData) 
router.post("/getAlltaxinvoicehdrData",dataController.getAlltaxinvoicehdrData) 
router.post("/TaxInvoiceDelteData",dataController.TaxInvoiceDeldetData)  
router.post("/getAllTaxInvoiceData",dataController.getAllTaxInvoiceDetData) 
router.post("/addTaxInvoiceTaxdetail",dataController.addTaxInvoiceTaxdetail) 
router.post("/TaxInvoicetaxDelteData",dataController.TaxInvoicetaxDelteData)
router.post("/getAllTaxInvoiceTaxData",dataController.getAllTaxInvoiceTaxData)  
router.post("/gettaxsearchdata",dataController.gettaxsearchdata)  
router.post("/getTaxInvoiceTax",dataController.getTaxInvoiceTax)  
router.post("/gettaxinvoiceDetail",dataController.gettaxinvoiceDetail) 
router.post("/addLoan",dataController.addLoan)  
router.get("/getLoan",dataController.getLoan)  
router.post("/updateLoan",dataController.updateLoan) 
router.post("/deleteLoan",dataController.deleteLoan) 
router.post("/addEmployeeLoan",dataController.addEmployeeLoan) 
router.post("/getEmployeeLoan",dataController.getEmployeeLoan) 
router.get("/getsearchEmpLoan",dataController.getsearchEmpLoan) 
router.post("/deleteEmployeeLoan",dataController.deleteEmployeeLoan) 
router.post("/updateEmployeeLoan",dataController.updateEmployeeLoan) 
router.get("/getApprovedBy",dataController.getApprovedBy) 
router.post("/addGrade",dataController.addGrade)
router.get("/allGradeData",dataController.allGradeData)
router.post("/deleteGrade",dataController.deleteGrade)
router.post("/updateGrade",dataController.updateGrade)
router.post("/addEmployeeCompany",dataController.addEmployeeCompany)
router.get("/allEmployeeCompanyData",dataController.allEmployeeCompanyData)
router.post("/deleteEmployeeCompany",dataController.deleteEmployeeCompany)
router.post("/updateEmployeeCompany",dataController.updateEmployeeCompany)
router.post("/addEmployeeFamily",dataController.addEmployeeFamily)
router.get("/allEmployeeFamilyData",dataController.allEmployeeFamilyData)
router.post("/deleteEmployeeFamily",dataController.deleteEmployeeFamily)
router.post("/updateEmployeeFamily",dataController.updateEmployeeFamily)
router.post("/addSalaryDetails",dataController.addSalaryDetails)
router.get("/allSalaryDetailsData",dataController.allSalaryDetailsData)
router.post("/deleteSalaryDetails",dataController.deleteSalaryDetails)
router.post("/updateSalaryDetails",dataController.updateSalaryDetails)
router.post("/addEmployeeLeave",dataController.addEmployeeLeave)
router.get("/allEmployeeLeaveData",dataController.allEmployeeLeaveData)
router.post("/deleteEmployeeLeave",dataController.deleteEmployeeLeave)
router.post("/updateEmployeeLeave",dataController.updateEmployeeLeave)
router.post("/addEmployeedoc", upload.fields([
  { name: 'ResumeFile', maxCount: 1 },
  { name: 'OfferLetter', maxCount: 1 },
  { name: 'JoiningLetter', maxCount: 1 },
  { name: 'ContractAndAgreement', maxCount: 1 },
  { name: 'aadhar_and_pan', maxCount: 1 }
]), dataController.addEmployeedoc);
router.post("/delemployeedoc",dataController.delemployeedoc)
router.post("/delemployeedoc",dataController.delemployeedoc)
router.get("/getAllemployeedoc",dataController.getAllemployeedoc)
router.post("/UpdateEmployeeImage",upload.single('Photos'),dataController.UpdateEmployeeImage)
router.post("/Employeedataupdate",upload.single('Photos'),dataController.Employeedataupdate)
router.post("/deleteemployeedata",dataController.  deleteemployeeper)
router.get("/getAllemployeedata",dataController.getAllemployeedata)
router.post("/getEmployeeDocument",dataController.getEmployeeDocument)
router.post("/addEmployeePersonalData", upload.single('Photos'),dataController.addEmployeePersonalData) 
router.post("/getID",dataController.getID) 
router.post("/getsiblings",dataController.getsiblings)
router.post("/getKids",dataController.getkids)
router.post("/getMartial",dataController.getMartial)
router.post("/addLeaveType",dataController.addLeaveType)
router.get("/getemployeemanager",dataController.getemployeemanager)
router.post("/addDailyattendance",dataController.addDailyattendance)
router.post("/getEmployeeFamily",dataController.getEmployeeFamily)
router.post("/getSalaryType",dataController.getSalaryType)
router.post("/getPayscale",dataController.getPayscale)
router.post("/Add_employee_bankdetails",upload.single('Bankbook_img'),dataController.Add_employee_bankdetails)
router.post("/Employeebankdetdelete",dataController.Employeebankdetdelete)
router.post("/updateEmployeebankdet",upload.single('Bankbook_img'),dataController.updateEmployeebankdet)
router.get("/getallEmployeebankdet",dataController.getallEmployeebankdet)
router.post("/getEmployeeSalary",dataController.getEmployeeSalary)
router.post("/getGrade", dataController.getGrade)
router.post("/getEmployeeBankDeatils",dataController.getEmployeeBankDeatils)
router.post("/getEmployeePersonaldet",dataController.getEmployeePersonaldet)
router.post("/getLoanID",dataController.getLoanID)
router.post("/getTaxInvoiceNo",dataController.getTaxInvoiceNo)
router.post("/addEmployeeAcademicDetails",dataController.addEmployeeAcademicDetails)
router.get("/allEmployeeAcademicDetails",dataController.allEmployeeAcademicDetails)
router.post("/updateEmployeeAcademicDetails",dataController.updateEmployeeAcademicDetails)
router.post("/deleteEmployeeAcademicDetails",dataController.deleteEmployeeAcademicDetails)
router.post("/addEmployeeIdentityDocument",dataController.addEmployeeIdentityDocument)
router.get("/allEmployeeIdentityDocument",dataController.allEmployeeIdentityDocument)
router.post("/updateEmployeeIdentityDocument",dataController.updateEmployeeIdentityDocument)
router.post("/deleteEmployeeIdentityDocument",dataController.deleteEmployeeIdentityDocument)
router.post("/getTaxInvoicePeriod",dataController.getTaxInvoicePeriod)
router.post("/getDocumentType",dataController.getDocumentType)
router.post("/getAcademicDetails",dataController.getAcademicDetails)
router.post("/getallProduct",dataController.getallProduct)
router.post("/getCustomerDetails",dataController.getCustomerDetails)
router.post("/addTaxInvoicedetail_list",dataController. addTaxInvoicedetail_list)
router.post("/ProductPrintHDR",dataController. ProductPrintHDR)
router.post("/ProductPrintDet",dataController. ProductPrintDet)
router.post("/getrelation",dataController. getrelation)
router.post("/taxInvoiceBalanceAmountCalculation",dataController. taxInvoiceBalanceAmountCalculation)
router.post("/TaxInvocieHdrPrint",dataController. TaxInvocieHdrPrint)
router.post("/TaxInvocieDetPrint",dataController. TaxInvocieDetPrint)
router.post("/taxinvoicetaxprint",dataController. taxinvoicetaxprint)
router.post("/getannoncementtype",dataController. getannoncementtype)
router.post("/getAnnouncementDetail",dataController. getAnnouncementDetail)
router.post("/UpdateProducthdr",dataController. UpdateProducthdr)
router.post("/UpdateProductdetails",dataController. UpdateProductdetails)
router.post("/getAnnouncement_Msg",dataController. getAnnouncement_Msg)
router.post("/getCurrentStockDetails",dataController. getCurrentStockDetails)
router.post("/getCurrentStockItemCode",dataController. getCurrentStockItemCode)
router.post("/addOpeningBalanceItemHdr",dataController. addOpeningBalanceItemHdr)
router.post("/getTotalStockValueDetails",dataController. getTotalStockValueDetails)
router.post("/openingitemhdr",dataController.openingitemhdr)
router.post("/openingitemdelhdr",dataController.openingitemdelhdr)
router.post("/getallOIHdr",dataController.getallOIHdr)
router.post("/addOpeningItemDetail",dataController.addOpeningItemDetail)
router.post("/deleteOpeningItemDetail",dataController.deleteOpeningItemDetail)
router.post("/allOpeningItemDetail",dataController.allOpeningItemDetail)
router.post("/getallOpeningItem",dataController.getallOpeningItem)
router.post("/openingItemSearch",dataController.openingItemSearch)
router.post("/getallOpeningItemDetail",dataController.getallOpeningItemDetail)
router.post("/addAnnounmentdetails",dataController.addAnnounmentdetails)
router.post("/deleteAnnouncement",dataController.deleteAnnouncement)
router.get("/allAnnouncementDetails",dataController.allAnnouncementDetails)
router.post("/updateAnnouncementDetails",dataController.updateAnnouncementDetails)
router.get("/getAnnouncementDetail",dataController.getAnnouncement)
router.post("/EmployeePersonalSC",dataController.EmployeePersonalSC)
router.post("/getAnnouncementDetails",dataController.getAnnouncementDetails)
router.post("/getcompanyshift",dataController.getcompanyshift)
router.post("/LeaveStatus",dataController.DashboardLeaveStatus)
router.post("/UpcomingBirthday",dataController.DashboardUpcomingBirthday)
router.post("/NewJoinee",dataController.DashboardNewJoinee)
router.post("/OverallAttendance",dataController.DashboardOverallAttendance)
router.post("/TeamList",dataController.DashboardTeamList)
router.post("/TeamListChart",dataController.DashboardTeamListChart)
router.post("/LeaveAuthorization",dataController.DashboardLeaveAuthorization)
router.post("/getEmpcompanyDetails",dataController.getEmpcompanyDetails)
router.post("/Quotation",dataController.Quotation)
router.post("/TaxInvoiceUpdate",dataController.TaxInvoiceUpdate)
router.post("/getItemCodeSalesDataQuote",dataController.getItemCodeSalesDataQuote)
router.post("/getotherpurtax",dataController.getotherpurtax)
router.post("/getothersalestax",dataController.getothersalestax)
router.post("/getOverallTAX",dataController.getOverallTAX)
router.post("/getAcademicDetailsSearchCretria",dataController.getAcademicDetailsSearchCretria)
router.post("/getIdentityDocuments",dataController.getIdentityDocuments)
router.post("/getTeamManager",dataController.getTeamManager)
router.post("/POTermsandConditions",dataController.POTermsandConditions)
router.post("/POTermsandConditionsDelete",dataController.POTermsandConditionsDelete)
router.get("/getallPOTermsandConditions",dataController.getallPOTermsandConditions)
router.post("/DCTermsandConditions",dataController.DCTermsandConditions)
router.post("/DCTermsandConditionsDelete",dataController.DCTermsandConditionsDelete)
router.get("/getallDCTermsandConditions",dataController.getallDCTermsandConditions)
router.post("/quoTermsandConditions",dataController.quoTermsandConditions)
router.post("/QuoTermsandConditionsDelete",dataController.QuoTermsandConditionsDelete)
router.get("/getallQuoTermsandConditions",dataController.getallQuoTermsandConditions)
router.post("/TITermsandConditions",dataController.TITermsandConditions)
router.post("/TITermsandConditionsDelete",dataController.TITermsandConditionsDelete)
router.get("/getallTITermsandConditions",dataController.getallTITermsandConditions)
router.post("/EmployeeCompanyISC",dataController. EmployeeCompanyISC)
router.post("/getItemCodeOtherSalesData",dataController.getItemCodeOtherSalesData)
router.post("/ProductCodeDetailOther",dataController.ProductCodeDetailOther)
router.post("/getInvocieType",dataController.getInvocieType)
router.post("/gettermsdc",dataController.gettermsdc)
router.post("/getQuotationTCDetailView",dataController.getQuotationTCDetailView)
router.post("/getPOTCDetailView",dataController.getPOTCDetailView)
router.post("/getTITerms",dataController.getTITerms)
router.post("/getUsercodenameBank",dataController.getUsercodenameBank)
router.post("/getVendorDetails",dataController.getVendorDetails)
router.post("/getIdentityDocumentSearchCretria",dataController.getIdentityDocumentSearchCretria)
router.post("/getItemCodeSalesDatatest",dataController.getItemCodeSalesDatatest)
router.post("/getcodetest",dataController.getcodetest)
router.post("/getCodeSalesDatatest",dataController.getCodeSalesDatatest)
router.post("/getitemsalsearchdatatest",dataController.getitemsalsearchdatatest)
router.post("/getFinancialDetailsSearchCretria",dataController.getFinancialDetailsSearchCretria)
router.post("/getFamilyDetailsSearchCretria",dataController.getFamilyDetailsSearchCretria)
router.post("/Terms",dataController.TermsDC)
router.post("/TermsQO",dataController.TermsQO)
router.post("/TermsPO",dataController.TermsPO)
router.post("/TermsTI",dataController.TermsTI)
router.post("/getEmpBankDetailsSC",dataController.getEmpBankDetailsSC)
router.post("/getESSmanager",dataController.getESSmanager)
router.post("/getLeaveType",dataController.getLeaveType)
router.post("/getSelectSlot",dataController.getSelectSlot)
router.post("/getGstReportAnalysis",dataController.getGstReportAnalysis)
router.post("/getDashBoardType",dataController.getDashBoardType)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getDeletedDeliveryChallan",dataController.getDeletedDeliveryChallan)
router.post("/getDeletedDcSearchData",dataController.getDeletedDcSearchData)
router.post("/getDeletedDcDetailView",dataController.getDeletedDcDetailView)
router.post("/getDeletedDcTerms",dataController.getDeletedDcTerms)
router.post("/getDeletedPurchaseOrder",dataController.getDeletedPurchaseOrder)
router.post("/getDeletedPoDetail",dataController.getDeletedPoDetail)
router.post("/getDeletedPoTaxDetail",dataController.getDeletedPoTaxDetail)
router.post("/getDeletedPoTerms",dataController.getDeletedPoTerms)
router.post("/getDeletedPoSearchData",dataController.getDeletedPoSearchData)
router.post("/getDeletedQuotation",dataController.getDeletedQuotation)
router.post("/getDeletedQuotationTaxDetailView",dataController.getDeletedQuotationTaxDetailView)
router.post("/getDeletedQuotationDetailView",dataController.getDeletedQuotationDetailView)
router.post("/getDeletedQuotationTerms",dataController.getDeletedQuotationTerms)
router.post("/getDeletedQuotationSearchData",dataController.getDeletedQuotationSearchData)
router.post("/getDeletedTaxInvoiceSearchData",dataController.getDeletedTaxInvoiceSearchData)
router.post("/getDeletedTaxInvoice",dataController.getDeletedTaxInvoice)
router.post("/getDeletedTaxInvoiceTax",dataController.getDeletedTaxInvoiceTax)
router.post("/getDeletedTaxinvoiceDetail",dataController.getDeletedTaxinvoiceDetail)
router.post("/getDeletedTaxIvoiceTerms",dataController.getDeletedTaxIvoiceTerms)
router.post("/getItemCode",dataController.getItemCode)
router.post("/getOpeningItemPeriod",dataController.getOpeningItemPeriod)
router.post("/getType",dataController.getType)
router.post("/getAccrual",dataController.getAccrual)
router.post("/getExceedLeave",dataController.getExceedLeave)
router.post("/getLeaveReason",dataController.getLeaveReason)
router.post("/getAnnouncement",dataController.getAnnouncement)
router.post("/getDateWiseItemStock",dataController.getDateWiseItemStock)
router.post("/EmployeeDashboardNewJoinee",dataController.EmployeeDashboardNewJoinee)
router.post("/EmployeeDashboardUpcomingBirthday",dataController.EmployeeDashboardUpcomingBirthday)
router.post("/EmployeeDashboardTotalLeave",dataController.EmployeeDashboardTotalLeave)
router.post("/DailyattendanceandTime",dataController.DailyattendanceandTime)
router.post("/addEmployeeHoliday",dataController.addEmployeeHoliday)
router.get("/allEmployeeHoliday",dataController.allEmployeeHoliday)
router.post("/updateEmployeeHoliday",dataController.updateEmployeeHoliday)
router.post("/getCustomerCodeDrop",dataController.getCustomerCodeDrop)
router.post("/getPendingCustomer",dataController.getPendingCustomer)
router.post("/getsearchLeavetypes",dataController.getsearchLeavetypes)
router.post("/getLeaveTypeSearch",dataController.getLeaveTypeSearch)
router.post("/getPendingStatus",dataController.getPendingStatus)
router.post("/updatePendingCustomer",dataController.updatePendingCustomer)
router.post("/getsearchHoliday",dataController.getsearchHoliday)
router.post("/AddBonusDetails",dataController.AddBonusDetails)
router.post("/DelBonusDetails",dataController.DelBonusDetails)
router.post("/UpdBonusDetails",dataController.UpdBonusDetails)
router.post("/GetBonusDetails",dataController.GetBonusDetails)
router.post("/addTDS",dataController.addTDS)
router.post("/updateTDS",dataController.updateTDS)
router.get("/allTDS",dataController.allTDS)
router.post("/deleteTDS",dataController.deleteTDS)
router.post("/SearchTDS",dataController.SearchTDS)
router.post("/addOtherAllowence",dataController.addOtherAllowence)
router.post("/updateOtherAllowence",dataController.updateOtherAllowence)
router.post("/deleteOtherAllowence",dataController.deleteOtherAllowence)
router.post("/allOtherAllowence",dataController.allOtherAllowence)
router.post("/allProfessionalTax",dataController.allProfessionalTax)
router.post("/addProfessionalTax",dataController.addProfessionalTax)
router.post("/updateProfessionalTax",dataController.updateProfessionalTax)
router.post("/deleteProfessionalTax",dataController.deleteProfessionalTax)
router.post("/addLoanType",dataController.addLoanType)
router.post("/updateLoanType",dataController.updateLoanType)
router.get("/allLoanType",dataController.allLoanType)
router.post("/deleteLoanType",dataController.deleteLoanType)
router.post("/addPfDetails",dataController.addPfDetails)
router.post("/updatePfDetail",dataController.updatePfDetail)
router.post("/allPfDetail",dataController.allPfDetail)
router.post("/deletePfDetail",dataController.deletePfDetail)
router.post("/ProfessionalTaxSC",dataController.ProfessionalTaxSC)
router.post("/BonusDetails",dataController.getBonusDetails)
router.post("/getPFContribution",dataController.getPFContribution)
router.post("/getLoanType",dataController.getLoanType)
router.post("/OtherAllowanceSC",dataController.OtherAllowanceSC)
router.post("/getDateWiseItemStock",dataController.getDateWiseItemStock)
router.post("/getdefCustomer",dataController.getdefCustomer)
router.post("/AddSalesSettings",dataController.AddSalesSettings)
router.post("/getAllPORethdrData",dataController.getAllPORethdrData)
router.post("/addPurchaseOrderReturnheader",dataController.addPurchaseOrderReturnheader)
router.post("/POdeleteRethdrData",dataController.POdeleteRethdrData)
router.post("/addPurchaseOrderRetdetail",dataController.addPurchaseOrderRetdetail)
router.post("/getAllPORetdetData",dataController.getAllPORetdetData)
router.post("/POdeleteRetdetData",dataController.POdeleteRetdetData)
router.post("/getPORetSearchData",dataController.getPORetSearchData)
router.post("/getDeletedPoRetSearchData",dataController.getDeletedPoRetSearchData)
router.post("/addPORettaxdetail",dataController.addPORettaxdetail)
router.post("/getAllPORettaxData",dataController.getAllPORettaxData)
router.post("/PODeleteRetTaxData",dataController.PODeleteRetTaxData)
router.post("/getitemcodevariant",dataController.getitemcodevariant)
router.post("/getDefaultoptions",dataController.getDefaultoptions)
router.post("/getSalesMode",dataController.getSalesMode)
router.post("/getSalesReturnAmountCalculation",dataController.getSalesReturnAmountCalculation)
router.post("/getReceivedGoods",dataController.getReceivedGoods)
router.post("/updateReceivedGoods",dataController.updateReceivedGoods)
router.post("/getReceivedGoodsReport",dataController.getReceivedGoodsReport)
router.post("/AddTransactionSettinngs",dataController.AddTransactionSettinngs)
router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
router.post("/getReceivedGoodsHelp",dataController.getReceivedGoodsHelp)
router.post("/addProject",dataController.addProject)
router.post("/updateProject",dataController.updateProject)
router.post("/deleteProject",dataController.deleteProject)
router.get("/getAllProject",dataController.getAllProject)
router.post("/addTask", upload.single('Documents'),dataController.addTask)
router.post("/updateTask",dataController.updateTask)
router.get("/getAllTask",dataController.getAllTask)
router.post("/addDailyLogin",dataController.addDailyLogin)
router.post("/addDailyTask", upload.array('Files', 10), dataController.addDailyTask);
router.post("/delDailyTask",dataController.delDailyTask)
router.post("/DCItemAmountCalculation",dataController.getDCItemAmountCalculation)
router.post("/getTaskstatus",dataController.getTaskstatus)
router.get("/getDailyTasks",dataController.getDailyTasks)
router.post("/DailytaskSC",dataController.DailytaskSC)
router.post("/updateTask",dataController.updateTask)
router.post("/DeleteTask",dataController.DeleteTask)
router.post("/getDCTotalAmountCalculation",dataController.getDCTotalAmountCalculation)
router.post("/PendingCustomer",dataController.PendingCustomer)
router.post("/updateBankAccount",upload.single('bank_paymentQRCode'),dataController.updateBankAccount)
router.post("/projectSC",dataController.projectSC)
router.post("/getProjectTask",dataController.getProjectTask)
router.post("/getDailyTask",dataController.getDailyTask)
router.post("/getPriority",dataController.getPriority)
router.post("/getProjectDetail",dataController.getProjectDetail)
router.post("/getTaskDetail",dataController.getTaskDetail)
router.post("/addProjectMapping",dataController.addProjectMapping)
router.post("/updateProjectMapping",dataController.updateProjectMapping)
router.post("/deleteProjectMapping",dataController.deleteProjectMapping)
router.post("/getProjectDrop",dataController.getProjectDrop)
router.post("/getProjectMapping",dataController.getProjectMapping)
router.post("/getTaskDetailReport",dataController.getTaskDetailReport)
router.post("/getTaskHourReport",dataController.getTaskHourReport)
router.post("/getTaskHourReportDetail",dataController.getTaskHourReportDetail)
router.get("/Getmanager",dataController.Getmanager)
router.post("/getProjectDetailReport",dataController.getProjectDetailReport)
router.get("/getProjectReport",dataController.getProjectReport)
router.post("/GradeSC",dataController.GradeSC)
router.post("/LoanSC",dataController.LoanSC)
router.post("/TaskMasterSC",dataController.TaskMasterSC)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/deleteLeave",dataController.deleteLeave)
router.post("/UpdateLeaveType",dataController.UpdateLeaveType)
router.post("/AnnouncementSearchCretria",dataController.AnnouncementSearchCretria)
router.post("/updPurchaseOrderheader",dataController.updPurchaseOrderheader)
router.post("/updQuotationheader",dataController.updQuotationheader)
router.post("/updDeliveryChallanheader",dataController.updDeliveryChallanheader)
router.post("/productImageUpdate",upload.single('Product_img'),dataController.productImageUpdate)
router.post("/Getticketandproject",dataController.Getticketandproject)
router.post("/GetProject",dataController.GetProject)
router.post("/DailyLogin",dataController.DailyLogin)
router.post("/DailyLogOUT",dataController.DailyLogOUT)
router.post("/Projectusercode",dataController.Projectusercode)
router.post("/deleteEmployeeHoliday",dataController.deleteEmployeeHoliday)
router.get("/GetCC",dataController.GetCC) //get company code dropdown
router.post("/InsertStockVal",dataController.InsertStockVal)
router.post("/updateStockVal",dataController.updateStockVal)
router.post("/updateStockValStatus",dataController.updateStockValStatus)
router.post("/deleteStockValue",dataController.deleteStockValue)
router.post("/StockSC",dataController.StockSC)
router.post("/EmpSearch",dataController.EmpSearch) //Dashboard Employee Search
router.post("/getAnnouncementDuration",dataController.getAnnouncementDuration)
router.post("/AddFileAttachment", upload.array('Files', 10), dataController.AddFileAttachment);
router.post("/ESSManager",dataController.ESSManager)
router.post("/GetClr",dataController.GetClr)
router.post("/getfiles",dataController.getfiles)
router.post("/getprojectSC",dataController.getprojectSC)
router.post("/PMSDashboard",dataController.PMSDashboard)
router.post("/getHolidayDate",dataController.getHolidayDate)
router.post("/PMSEmployeechart",dataController.PMSEmployeechart)
router.post("/AddSalaryCriteria",dataController.AddSalaryCriteria)
router.post("/DeleteSalaryCriteria",dataController.DeleteSalaryCriteria)
router.post("/UpdateSalaryCriteria",dataController.UpdateSalaryCriteria)
router.post("/GeneratePaySlip",dataController.GeneratePaySlip)
router.post("/GetPaysllipSC",dataController.GetPaysllipSC)
//router.post("/AddSearchCriteria", dataController.AddSearchCriteria)
router.post("/getboolean", dataController.getboolean)
router.post("/mailgenerating", dataController.mailgenerating)
router.post("/savePdf", upload.single("pdf"), dataController.savePDFToPath);
router.post("/GetPaysllipTemplate", dataController.GetPaysllipTemplate)
router.post("/sendPayslipEmails", dataController.sendPayslipEmails)
router.post("/salarySearchoption", dataController.salarySearchoption)
router.post("/UpdateSalary", dataController.UpdateSalary)
router.post("/salaryDelete", dataController.salaryDelete)
router.post("/AddEmpDoc",dataController.AddEmpDoc)
router.post("/delempdoc",dataController.delempdoc)
router.post("/getAllempdoc",dataController.getAllempdoc)
router.post("/getDocument",dataController.getDocument)
router.post("/getempdoc",dataController.getempdoc)
router.post("/getapplyLeavetype",dataController.getapplyLeavetype)
router.post("/updateempDoc",dataController.updateempDoc)
router.post("/getEmployeeTotalLeaveBalance",dataController.getEmployeeTotalLeaveBalance)
router.post("/getEmployeeLeavesearch",dataController.getEmployeeLeavesearch)
router.post("/sendAutoMail",dataController.sendAutoMail)
router.post("/addAssertAllocationReturnHdr",dataController.addAssertAllocationReturnHdr)
router.post("/getAssertAllocationReturnHdr",dataController.getAssertAllocationReturnHdr)
router.post("/addAssetsAllocationReturnDeatils",dataController.addAssetsAllocationReturnDetails)
router.post("/getAssetsAllocationReturnDeatils",dataController.getAssetsAllocationReturnDetails)
router.post("/getallAssetsAllocationReturn",dataController.getallAssetsAllocationReturn)
router.post("/searchCriteriaAssertReturn",dataController.searchCriteriaAssertReturn)
router.post("/getAssertReturnDetail",dataController.getAssertReturnDetail)
router.post("/assetsEmployeeId",dataController.assetsEmployeeId)
router.post("/updateRoleRights",dataController.updateRoleRights)
router.post("/salesTermsandCondition",dataController.salesTermsandCondition)
router.post("/deleteSalesTermsandCondition",dataController.deleteSalesTermsandCondition)
router.post("/getAllSalesTermsandCondition",dataController.getAllSalesTermsandCondition)
router.post("/termsandCondition",dataController.termsandCondition)
router.post("/getTermsandConditionSales",dataController.getTermsandConditionSales)
router.post("/getDeletedTermsSales",dataController.getDeletedTermsSales)
router.post("/customerCodeDropdown",dataController.customerCodeDropdown)
router.post("/AddFinacnialyearlockscreen",dataController.AddFinacnialyearlockscreen)
router.post("/deleteFinacnialyearlockscreen",dataController.deleteFinacnialyearlockscreen)
router.post("/SelectFinacnialyearlockscreen",dataController.SelectFinacnialyearlockscreen)
router.post("/UpdateFinacnialyearlockscreen",dataController.UpdateFinacnialyearlockscreen)
router.post("/deleteFinacnialyearlockscreenGrid",dataController.deleteFinacnialyearlockscreenGrid)
router.post("/getFinacnialyearlockscreenSearchCriteria",dataController.getFinacnialyearlockscreenSearchCriteria)
router.post("/getLockType", dataController.getLockType)
router.post("/vendorCodeDropdown",dataController.vendorCodeDropdown)
router.post("/UpdateFinacnialyearlock",dataController.UpdateFinacnialyearlock)
router.post("/TotalActiveEmployees",dataController.TotalActiveEmployees)
router.post("/TotalNetEarnings",dataController.TotalNetEarnings)
router.post("/TotalPayslips",dataController.TotalPayslips)
router.post("/EmployeeDocSC",dataController.EmployeeDocSC)
router.post("/PrintTemplates",dataController.PrintTemplates)
router.post("/AddPrintTemplate", dataController.AddPrintTemplate)
router.post("/Templatesearch",dataController.Templatesearch)
router.post("/getPrint",dataController.getPrint)
router.post("/getcopies",dataController.getcopies)
router.post("/getSalesItemCode",dataController.getSalesItemCode)
router.post("/WeekOff",dataController.WeekOff)
router.post("/addCRMClient",dataController.addCRMClient)
router.post("/updateCRMClient",dataController.updateCRMClient)
router.post("/deleteCRMClient",dataController.deleteCRMClient)
router.post("/getCRMClient",dataController.getCRMClient)
router.post("/addCRMContacts",upload.single('Image'),dataController.addCRMContacts)
router.post("/updateCRMContacts",dataController.updateCRMContacts)
router.post("/deleteCRMContacts",dataController.deleteCRMContacts)
router.post("/getCRMContacts",dataController.getCRMContacts)
router.get("/getCRMContactName",dataController.getCRMContactName)
router.post("/GenerateEmployee",dataController.GenerateEmployee)
router.post("/openingTicketSearch",dataController.openingTicketSearch)
router.post("/getUserCode",dataController.getUserCode)
router.post("/AddWeekOff",dataController.AddWeekOff)
router.post("/deleteWeekOff",dataController.deleteWeekOff)
router.post("/updateWeekOff",dataController.updateWeekOff)
router.post("/getWeekOff",dataController.getWeekOff)
router.post("/AddGenerateEmployee",dataController.AddGenerateEmployee)
router.post("/deleteGenerateEmployee",dataController.deleteGenerateEmployee)
router.post("/getGenerateEmployee",dataController.getGenerateEmployee)
router.post("/GetUserCheckIN",dataController.GetUserCheckIN)
router.post("/FetchWeekOff",dataController.FetchWeekOff)
router.post("/FetchGenerateEmployee",dataController.FetchGenerateEmployee)
router.post("/getLeaveStatus",dataController.getLeaveStatus)
router.post("/AddPMSSetting",dataController.AddPMSSetting)
router.post("/deletePMSsettings",dataController.deletePMSsettings)
router.post("/GetPMSsettings",dataController.GetPMSsettings)
router.post("/PMSsettingsUpdate",dataController.PMSsettingsUpdate)
router.post("/SettingEmployeeUpdate",dataController.SettingEmployeeUpdate)
router.post("/ESSEmployeeDashboard",dataController.ESSEmployeeDashboard)
router.post("/getAnnouncementText",dataController.getAnnouncementText)
router.post("/getManager",dataController.getManager)
router.post("/getCheckInStatus",dataController.getCheckInStatus)
router.post("/Getpayslip",dataController.Getpayslip)
router.post("/getEmployeeId", dataController.getEmployeeId)
router.post("/DashboardOverallAttendanceData", dataController.DashboardOverallAttendanceData)
router.post("/getEmployeeCheckInCheckOut", dataController.getEmployeeCheckInCheckOut)
router.post("/getTaskUserID", dataController.getTaskUserID)
router.post("/PMS_Client_infoInsert", dataController.PMS_Client_infoInsert)
router.post("/GetPaymentMode", dataController.GetPaymentMode)
router.post("/GetPaymentType", dataController.GetPaymentType)
router.post("/GetClientInfoSearch", dataController.GetClientInfoSearch)
router.post("/uploadImage", upload2.single("image"), dataController.uploadImages);
router.post("/PMS_Client_infoLoopUpdate", dataController.PMS_Client_infoLoopUpdate)
router.post("/PMS_Client_infoDelete", dataController.PMS_Client_infoDelete)
router.post("/PMS_Client_infoLoopDelete", dataController.PMS_Client_infoLoopDelete)
router.post("/Client_PaymentInsert", dataController.Client_PaymentInsert)
router.post("/Client_PaymentUpdate", dataController.Client_PaymentUpdate)
router.post("/Client_PaymentDelete", dataController.Client_PaymentDelete)
router.post("/Client_PaymentLoopUpdate", dataController.Client_PaymentLoopUpdate)
router.post("/Client_PaymentLoopDelete", dataController.Client_PaymentLoopDelete)
router.post("/PMS_Client_infoUpdate", dataController.PMS_Client_infoUpdate)
router.post("/GetClient_PaymentData", dataController.GetClient_PaymentData)
router.post("/GetClient_PaymentDataSearch", dataController.GetClient_PaymentDataSearch)
router.post("/CRM_ContactInfoInsert", upload.single('Image'), dataController.CRM_ContactInfoInsert)
router.post("/CRM_ContactInfoUpdate", upload.single('Image'), dataController.CRM_ContactInfoUpdate)
router.post("/CRM_ContactInfoDelete", dataController.CRM_ContactInfoDelete)
router.post("/ClientPaymentExcel", dataController.getClientPaymentExcel)
router.post("/ContactInfoCompanyName", dataController.CRM_ContactInfoCompanyName)
router.post("/CompanySearch", dataController.CompanySearch)
router.post("/CRM_SourceInsert", dataController.CRM_SourceInsert)
router.post("/CRM_SalesPersonMasterInsert", dataController.CRM_SalesPersonMasterInsert)
router.post("/CRM_SalesPersonMasterUpdate", dataController.CRM_SalesPersonMasterUpdate)
router.post("/CRM_SalesPersonMasterDelete", dataController.CRM_SalesPersonMasterDelete)
router.post("/defaultCompanyNames", dataController.defaultCompanyNames)
router.post("/defaultContactsName", dataController.defaultContactsName)
router.post("/companyToContact", dataController.companyToContact)
router.post("/contactToCompany", dataController.contactToCompany)
router.post("/getDateRangeCRM", dataController.getDateRangeCRM)
router.post("/CRM_NewCompanyInsert", dataController.CRM_NewCompanyInsert)
router.post("/getNewCompany", dataController.getNewCompany)
router.post("/updateNewCompanyStage", dataController.updateNewCompanyStage)
router.post("/CRM_NewCompanyDelete", dataController.CRM_NewCompanyDelete)
router.post("/getOpportunityDetails", dataController.getOpportunityDetails)
router.post("/CRM_NewCompanyUpdate", dataController.CRM_NewCompanyUpdate)
router.post("/CRM_SalesTeam_DetailsInsert", dataController.CRM_SalesTeam_DetailsInsert)
router.post("/CRM_SalesTeam_DetailsUpdate", dataController.CRM_SalesTeam_DetailsUpdate)
router.post("/CRM_SalesTeam_DetailsDelete", dataController.CRM_SalesTeam_DetailsDelete)
router.post("/CRM_ActivityInsert",upload.single('Attachments'), dataController.CRM_ActivityInsert)
router.post("/CRM_ActivityUpdate", dataController.CRM_ActivityUpdate)
router.post("/CRM_ActivityDelete", dataController.CRM_ActivityDelete)
router.post("/getCustomerDropdown", dataController.getCustomerDropdown)
router.post("/updateNewCompanyPeriority", dataController.updateNewCompanyPeriority)
router.post("/GetSalesperson", dataController.GetSalesperson)
router.post("/CRM_ActivityDelete", dataController.CRM_ActivityDelete)
router.post("/CRM_AddContactInsert", dataController.CRM_AddContactInsert)
router.post("/CRM_AddContactUpdate", dataController.CRM_AddContactUpdate)
router.post("/CRM_AddContactDelete", dataController.CRM_AddContactDelete)
router.post("/CRM_LogNoteInsert", dataController.CRM_LogNoteInsert)
router.post("/CRM_LogNoteUpdate", dataController.CRM_LogNoteUpdate)
router.post("/CRM_LogNoteDelete", dataController.CRM_LogNoteDelete)
router.post("/CRM_MeetingSubjectInsert", dataController.CRM_MeetingSubjectInsert)
router.post("/CRM_MeetingSubjectUpdate", dataController.CRM_MeetingSubjectUpdate)
router.post("/CRM_MeetingSubjectDelete", dataController.CRM_MeetingSubjectDelete)
router.post("/CRM_CampaignInsert", dataController.CRM_CampaignInsert)
router.post("/CRM_CampaignUpdate", dataController.CRM_CampaignUpdate)
router.post("/CRM_CampaignDelete", dataController.CRM_CampaignDelete)
router.post("/CRM_MediumInsert", dataController.CRM_MediumInsert)
router.post("/CRM_MediumUpdate", dataController.CRM_MediumUpdate)
router.post("/CRM_MediumDelete", dataController.CRM_MediumDelete)
router.post("/CRM_SalesPurchaseInserts", dataController.CRM_SalesPurchaseInsert)
router.post("/CRM_SalesPurchaseUpdate", dataController.CRM_SalesPurchaseUpdate)
router.post("/CRM_SalesPurchaseDelete", dataController.CRM_SalesPurchaseDelete)
router.post("/CRM_NewEventInsert", dataController.CRM_NewEventInsert)
router.post("/CRM_NewEventUpdate", dataController.CRM_NewEventUpdate)
router.post("/CRM_NewEventDelete", dataController.CRM_NewEventDelete)
router.post("/CRM_MessageInsert", dataController.CRM_MessageInsert)
router.post("/CRM_MessageUpdate", dataController.CRM_MessageUpdate)
router.post("/CRM_MessageDelete", dataController.CRM_MessageDelete)
router.post("/GetSalesperson", dataController.GetSalesperson)
router.post("/GetSalespersonALL", dataController.GetSalespersonALL)
router.post("/salesPersonDropdown", dataController.salesPersonDropdown)
router.post("/GetDataContactInfo", dataController.GetDataContactInfo)
router.post("/GetDataContact", dataController.GetDataContact)
router.post("/getContactEmail", dataController.getContactEmail)
router.post("/getContacts", dataController.getContacts)
router.post("/getContactsDetails", dataController.getContactsDetails)
router.post("/getSource", dataController.getSource)
router.post("/getMedium", dataController.getMedium)
router.post("/CRM_LogNoteGet", dataController.CRM_LogNoteGet)
router.post("/searchSource", dataController.searchSource)
router.post("/mediumSearch", dataController.mediumSearch)
router.post("/CampaignSearch", dataController.CampaignSearch)
router.post("/SearchSalesperson", dataController.SearchSalesperson)
router.post("/getCampaign", dataController.getCampaign)
router.post("/CRM_Tag_MasterInsert", dataController.CRM_Tag_MasterInsert)
router.post("/CRM_Tag_MasterUpdate", dataController.CRM_Tag_MasterUpdate)
router.post("/CRM_Tag_MasterDelete", dataController.CRM_Tag_MasterDelete)
router.post("/CRM_SalesTeam_HDRInsert", dataController.CRM_SalesTeam_HDRInsert)
router.post("/CRMClientSearch", dataController.CRMClientSearch)
router.post("/GetTeam", dataController.GetTeam)
router.post("/GetSalesTeam", dataController.GetSalesTeam)
router.post("/GetTeamName", dataController.GetTeamName)
router.post("/GetActivity", dataController.GetActivity)
router.post("/GetContactClient", dataController.GetContactClient)
router.post("/GetContactInfo", dataController.GetContactInfo)
router.post("/activitySearch", dataController.activitySearch)
router.post("/TagSearch", dataController.TagSearch)
router.post("/getTagName", dataController.getTagName)
router.post("/GetActivityAll", dataController.GetActivityAll)
router.post("/GetContactInfoData", dataController.GetContactInfoData)
router.post("/GetContactInfoDetails", dataController.GetContactInfoDetails)
router.post("/GetCompanyMonth", dataController.GetCompanyMonth)
router.post("/SalesTeamSearch", dataController.SalesTeamSearch)
router.post("/Forecastsearch", dataController.Forecastsearch)
router.post("/CRM_CompanyDateUpdate", dataController.CRM_CompanyDateUpdate)
router.post("/CRM_CompanySearch", dataController.CRM_CompanySearch)
router.post("/CRM_MarkUP", dataController.CRM_MarkUP)
router.post("/SalesTeamChart", dataController.SalesTeamChart)
router.post("/Pipelinechart", dataController.Pipelinechart)
router.post("/CRM_Lose_Insert", dataController.CRM_Lose_Insert)
// router.post("/CRM_Lose_Update", dataController.CRM_Lose_Update)
// router.post("/CRM_Lose_Delete", dataController.CRM_Lose_Delete)
router.post("/CRM_Lose_Select", dataController.CRM_Lose_Select)
router.post("/PipelineDetailChart", dataController.PipelineDetailChart)
router.post("/ActivityChart", dataController.ActivityChart)
router.post("/getDomain", dataController.getDomain)
router.post("/GetAllMeeting", dataController.GetAllMeeting)
router.post("/SalesTeamDetailChart", dataController.SalesTeamDetailChart)
router.post("/GetActive", dataController.GetActive)
router.post("/GetRevenue",dataController.GetRevenue)
router.post("/GetAllEvent",dataController.GetAllEvent)
router.post("/CRMSalesTeamUpdateGrid", dataController.CRMSalesTeamUpdateGrid)
router.post("/CRM_LoseSC",dataController.CRM_LoseSC)
router.post("/ActivityDetailChart",dataController.ActivityDetailChart)
router.get("/CRM_PV",dataController.CRM_PV)
router.post("/GetCalendarEvent",dataController.GetCalendarEvent)
router.post("/CRM_SalesTeam_HDRUpdate", dataController.CRM_SalesTeam_HDRUpdate)
router.post("/ContactSearch", dataController.ContactSearch)
router.post("/getSecondaryuom", dataController.getSecondaryuom)
router.post("/getCount", dataController.getCount)
router.post("/EmpStatus", dataController.EmpStatus)
router.post("/getTaskHourReportLeave", dataController.getTaskHourReportLeave)
router.post("/UOMConverterInsert", dataController.UOMConverterInsert)
router.post("/getItemVariant", dataController.getItemVariant)
router.post("/getPay", dataController.getPay)
router.post("/addSalesOrderHdr", dataController.addSalesOrderHdr)
router.post("/addSalesOrderDetail", dataController.addSalesOrderDetail)
router.post("/getCategoriesMaster", dataController.getCategoriesMaster)
router.post("/addSelectionSalesOrderHdr", dataController.addSelectionSalesOrderHdr)
router.post("/addSelectionSalesOrderDetail", dataController.addSelectionSalesOrderDetail)
router.post("/Recenty_ViewedInsert", dataController.Recenty_ViewedInsert)
router.post("/getCategories", dataController.getCategories)
router.post("/getSalesOrder", dataController.getSalesOrder)
router.post("/Recenty_ViewedDelete", dataController.Recenty_ViewedDelete)


module.exports = router;