name: IIS Auto Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Download code
        uses: actions/checkout@v4
            
      - name: Frontend build
        run: |
          npm install
          npm run build
          
      - name: Copy frontend build to IIS
        run: |
          xcopy /E /Y /I build "C:\inetpub\wwwroot\OS\build"
      # -------- BACKEND --------
      - name: Backend install
        run: |
          cd backend
          npm install
      - name: Restart backend
        run: |
          pm2 restart os-backend
